DotNetEfCore/Controllers/TugasController.cs
using DotnetEfCore.DataContext;
using Microsoft.AspNetCore.Mvc;

namespace DotNetEfCore.Controllers
{
    public class TugasController : Controller
    {
        private readonly ApplicationDbContext _context;
        public TugasController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult GetAllTokoKomputer()
        {
            IEnumerable<TokoKomputerEntity> data = _context.TokoKomputerEntities.ToList();
            return View(data);
        }

        [HttpGet]
        public IActionResult DetailsTokoKomputer(int? id)
        {
            TokoKomputerEntity data = _context.TokoKomputerEntities.Find(id);
            return View(data);
        }

        [HttpGet]
        public IActionResult AddTokoKomputer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveTokoKomputer([Bind("Nama, Kategori, Jumlah, Harga")] TokoKomputerEntity request)
        {
            // add ke entity
            _context.TokoKomputerEntities.Add(request);
            // commit to database
            _context.SaveChanges();

            return Redirect("GetAllTokoKomputer");
        }

        [HttpGet]
        public IActionResult EditTokoKomputer(int? id)
        {
            var entity = _context.TokoKomputerEntities.Find(id);
            return View(entity);
        }

        [HttpGet]
        public IActionResult DeleteTokoKomputer(int? id)
        {
            var entity = _context.TokoKomputerEntities.Find(id);
            if (entity == null)
            {
                return Redirect("GetAll");
            }
            // remove from entity
            _context.TokoKomputerEntities.Remove(entity);
            // commit to database
            _context.SaveChanges();
            return RedirectToAction("GetAllTokoKomputer");
        }

        [HttpPost]
        public IActionResult UpdateTokoKomputer([Bind("Id, Nama, Kategori, Jumlah, Harga")] TokoKomputerEntity request)
        {
            // update entity
            _context.TokoKomputerEntities.Update(request);
            // commit to database
            _context.SaveChanges();
            return Redirect("GetAllTokoKomputer");
        }









        public IActionResult GetAllTokoGame()
        {
            IEnumerable<TokoGameEntity> data = _context.TokoGameEntities.ToList();
            return View(data);
        }

        [HttpGet]
        public IActionResult DetailsTokoGame(int? id)
        {
            TokoGameEntity data = _context.TokoGameEntities.Find(id);
            return View(data);
        }

        [HttpGet]
        public IActionResult AddTokoGame()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveTokoGame([Bind("Nama, Genre, Jumlah, Tahun, Harga")] TokoGameEntity request)
        {
            // add ke entity
            _context.TokoGameEntities.Add(request);
            // commit to database
            _context.SaveChanges();

            return Redirect("GetAllTokoGame");
        }

        [HttpGet]
        public IActionResult EditTokoGame(int? id)
        {
            var entity = _context.TokoGameEntities.Find(id);
            return View(entity);
        }

        [HttpGet]
        public IActionResult DeleteTokoGame(int? id)
        {
            var entity = _context.TokoGameEntities.Find(id);
            if (entity == null)
            {
                return Redirect("GetAll");
            }
            // remove from entity
            _context.TokoGameEntities.Remove(entity);
            // commit to database
            _context.SaveChanges();
            return RedirectToAction("GetAllTokoGame");
        }

        [HttpPost]
        public IActionResult UpdateTokoGame([Bind("Id, Nama, Genre, Jumlah, Tahun, Harga")] TokoGameEntity request)
        {
            // update entity
            _context.TokoGameEntities.Update(request);
            // commit to database
            _context.SaveChanges();
            return Redirect("GetAllTokoGame");
        }









        public IActionResult GetAllDataTamu()
        {
            IEnumerable<DataTamuEntity> data = _context.DataTamuEntities.ToList();
            return View(data);
        }

        [HttpGet]
        public IActionResult DetailsDataTamu(int? id)
        {
            DataTamuEntity data = _context.DataTamuEntities.Find(id);
            return View(data);
        }

        [HttpGet]
        public IActionResult AddDataTamu()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveDataTamu([Bind("Nama, Kota, NoWa, NoTlp")] DataTamuEntity request)
        {
            // add ke entity
            _context.DataTamuEntities.Add(request);
            // commit to database
            _context.SaveChanges();

            return Redirect("GetAllDataTamu");
        }

        [HttpGet]
        public IActionResult EditDataTamu(int? id)
        {
            var entity = _context.DataTamuEntities.Find(id);
            return View(entity);
        }

        [HttpGet]
        public IActionResult DeleteDataTamu(int? id)
        {
            var entity = _context.DataTamuEntities.Find(id);
            if (entity == null)
            {
                return Redirect("GetAllDataTamu");
            }
            // remove from entity
            _context.DataTamuEntities.Remove(entity);
            // commit to database
            _context.SaveChanges();
            return RedirectToAction("GetAllDataTamu");
        }

        [HttpPost]
        public IActionResult UpdateDataTamu([Bind("Id, Nama, Kota, NoWa, NoTlp")] DataTamuEntity request)
        {
            // update entity
            _context.DataTamuEntities.Update(request);
            // commit to database
            _context.SaveChanges();
            return Redirect("GetAllDataTamu");
        }

    }
}

DotNetEfCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>RapidMail - PT Rapid Teknologi Indonesia</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/images/logo.png" rel="icon">
    <link href="~/images/logo.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900&display=swap" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="~/css/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/css/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/css/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/css/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/main.css" rel="stylesheet">
    <style type="text/css">
        table.scroll thead {
            display: table;
        }

        table.scroll tbody {
            display: block;
            height: 320px;
            overflow: auto;
            float: left;
            width: 1080px;
        }

            table.scroll tbody tr {
                display: table;
            }
    </style>

</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="container d-flex align-items-center justify-content-between">
            <a href="/" class="logo d-flex align-items-center me-auto me-lg-0">
                <h1><img src="~/images/logo2.png" class="rounded float-left" alt="LogoRapidTech"></h1>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li>
                        <a asp-controller="Tugas" asp-action="GetAllTokoKomputer">
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pc-display" viewBox="0 0 16 16">
                                    <path d="M8 1a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V1Zm1 13.5a.5.5 0 1 0 1 0 .5.5 0 0 0-1 0Zm2 0a.5.5 0 1 0 1 0 .5.5 0 0 0-1 0ZM9.5 1a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5ZM9 3.5a.5.5 0 0 0 .5.5h5a.5.5 0 0 0 0-1h-5a.5.5 0 0 0-.5.5ZM1.5 2A1.5 1.5 0 0 0 0 3.5v7A1.5 1.5 0 0 0 1.5 12H6v2h-.5a.5.5 0 0 0 0 1H7v-4H1.5a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5H7V2H1.5Z" />
                                </svg>&nbsp;
                                Toko Komputer
                            </span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a asp-controller="Tugas" asp-action="GetAllTokoGame">
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-controller" viewBox="0 0 16 16">
                                    <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1v-1z" />
                                    <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729c.14.09.266.19.373.297.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466.206.875.34 1.78.364 2.606.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527-1.627 0-2.496.723-3.224 1.527-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.34 2.34 0 0 1 .433-.335.504.504 0 0 1-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a13.748 13.748 0 0 0-.748 2.295 12.351 12.351 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.354 12.354 0 0 0-.339-2.406 13.753 13.753 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27-1.036 0-2.063.091-2.913.27z" />
                                </svg>&nbsp;
                                Toko Game
                            </span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a asp-controller="Tugas" asp-action="GetAllDataTamu">
                            <span>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16">
                                    <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
                                    <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z" />
                                </svg>&nbsp;
                                Data Tamu
                            </span>
                        </a>
                    </li>
                </ul>
            </nav><!-- .navbar -->

            <a class="btn-book-a-table" href="#book-a-table">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill-x" viewBox="0 0 16 16">
                    <path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm-9 8c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Z" />
                    <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm-.646-4.854.646.647.646-.647a.5.5 0 0 1 .708.708l-.647.646.647.646a.5.5 0 0 1-.708.708l-.646-.647-.646.647a.5.5 0 0 1-.708-.708l.647-.646-.647-.646a.5.5 0 0 1 .708-.708Z" />
                </svg>
                Logout
            </a>
            <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
            <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

        </div>
    </header><!-- End Header -->
    <main id="main">
        @RenderBody()
    </main>

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="container">
            <div class="row gy-3">
                <div class="col-lg-3 col-md-6 d-flex">
                    <i class="bi bi-geo-alt icon"></i>
                    <div>
                        <h4>Address</h4>
                        <p>
                            PT Rapid Teknologi Indonesia <br>
                            - BSD, Indonesia<br>
                        </p>
                    </div>

                </div>

                <div class="col-lg-3 col-md-6 footer-links d-flex">
                    <i class="bi bi-telephone icon"></i>
                    <div>
                        <h4>Reservations</h4>
                        <p>
                            <strong>Phone:</strong> +6221 50835637<br>
                            <strong>whatsapp:</strong> +6281296437737<br>
                            <strong>Email:</strong> hello@rapidtech.id<br>
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 footer-links d-flex">
                    <i class="bi bi-clock icon"></i>
                    <div>
                        <h4>Opening Hours</h4>
                        <p>
                            <strong>Mon-Fat: 09AM - 06PM</strong> <br>
                            Saturday: Closed<br>
                            Sunday: Closed
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Follow Us</h4>
                    <div class="social-links d-flex">
                        <a href="https://web.facebook.com/rapidtechid/?_rdc=1&_rdr" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="https://www.instagram.com/rapidtechid/" class="instagram"><i class="bi bi-instagram"></i></a>
                        <a href="https://www.linkedin.com/company/rapidtechid/?viewAsMember=true" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Rapid Technology</span></strong>. All Rights Reserved
            </div>
        </div>

    </footer><!-- End Footer -->
    <!-- End Footer -->

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="~/css/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/css/vendor/aos/aos.js"></script>
    <script src="~/css/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/css/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/css/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/css/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>


</body>

</html>